server:
  port: 9090
spring:
  application:
    name: WEBSOCKET-SERVER-1
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为 false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是 templates，可以不用配置
    prefix: classpath:/templates
    suffix: .html
  mvc:
    static-path-pattern: /static/**
